version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      REACT_APP_API: ${REACT_APP_API}
      REACT_APP_AUTH: ${REACT_APP_AUTH}
      REACT_APP_AUTH_LOG: ${REACT_APP_AUTH_LOG}
      REACT_APP_CLIENT: ${REACT_APP_CLIENT}
      REACT_APP_CONTENT_ABOUT: ${REACT_APP_CONTENT_ABOUT}
      REACT_APP_CONTENT_DATA: ${REACT_APP_CONTENT_DATA}
      REACT_APP_CONTENT_DATA_MODEL: ${REACT_APP_CONTENT_DATA_MODEl}
      REACT_APP_CONTENT_HOME: ${REACT_APP_CONTENT_HOME}
      REACT_APP_CONTENT_IMPRINT: ${REACT_APP_CONTENT_IMPRINT}
      REACT_APP_CONTENT_LOGOS: ${REACT_APP_CONTENT_LOGOS}
      REACT_APP_CONTENT_PRIVACY: ${REACT_APP_CONTENT_PRIVACY}
      REACT_APP_DESCRIPTION: ${REACT_APP_DESCRIPTION}
      REACT_APP_FAVICON: ${REACT_APP_FAVCION}
      REACT_APP_LOGO: ${REACT_APP_LOGO}
      REACT_APP_NAME: ${REACT_APP_NAME}
      REACT_APP_REALM: ${REACT_APP_REALM}
