version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      REACT_APP_API: ${REACT_APP_API}
      REACT_APP_AUTH: ${REACT_APP_AUTH}
      REACT_APP_CLIENT: ${REACT_APP_CLIENT}
      REACT_APP_HOME_TEXTS: ${REACT_APP_HOME_TEXTS}
      REACT_APP_NAME: ${REACT_APP_NAME}
      REACT_APP_REALM: ${REACT_APP_REALM}
      REACT_APP_AUTH_LOG: ${REACT_APP_AUTH_LOG}
