export { NampiProvider } from "./components/NampiProvider";
export {
    useAct,
    useActs,
    useAspect,
    useAspectCreate,
    useAspectDelete,
    useAspects,
    useAspectUpdate,
    useAuthor,
    useAuthors,
    useEvent,
    useEventCreate,
    useEventDelete,
    useEvents,
    useEventUpdate,
    useGroup,
    useGroupCreate,
    useGroupDelete,
    useGroups,
    useGroupUpdate,
    useHierarchy,
    usePerson,
    usePersonCreate,
    usePersonDelete,
    usePersons,
    usePersonUpdate,
    usePlace,
    usePlaceCreate,
    usePlaceDelete,
    usePlaces,
    usePlaceUpdate,
    useSource,
    useSourceCreate,
    useSourceDelete,
    useSources,
    useSourceUpdate,
    useTypes,
    useUser
} from "./hooks/dataHooks";
export { useAuth } from "./hooks/useAuth";
export { usePropertyIris } from "./hooks/usePropertyIris";
export { namespaces } from "./namespaces";
export type {
    Act,
    ActsQuery,
    Aspect,
    AspectMutationPayload,
    AspectsQuery,
    Author,
    AuthorsQuery,
    CollectionNav,
    CollectionQuery,
    Entity,
    Event,
    EventMutationPayload,
    EventsQuery,
    FetchCollectionResult,
    FetchResult,
    Group,
    GroupMutationPayload,
    GroupsQuery,
    Hierarchy,
    HierarchyItem,
    HierarchyQuery,
    Item,
    Literal,
    LiteralDateTime,
    LiteralNumber,
    LiteralString,
    Person,
    PersonMutationPayload,
    PersonsQuery,
    Place,
    PlaceMutationPayload,
    PlacesQuery,
    Source,
    SourceLocation,
    SourceMutationPayload,
    SourcesQuery,
    Type,
    TypesQuery,
    User
} from "./types";

